[package]
name = "common"
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
borsh.workspace = true
bytes.workspace = true
